version: "3.9"
services:
  postgres:
    container_name: pgdb
    image: postgres:13.3
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pgpwd4project"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks: ['mynetwork']

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: "pgpwd4project"
    ports:
      - "5050:80"
    networks: ['mynetwork']


networks: {mynetwork: {}}
